In [3]:
import pandas as pd

In [1]:
from sklearn.preprocessing import StandardScaler

In [4]:
data = pd.read_csv("/Users/zahiramohammed/Desktop/DAPM_dataset_new.csv") #read the dataset

In [5]:
# Data Cleaning
# -----No cleaning needed for this dataset(as it is previously cleaned data)------

# Data Integration
# -----Only one dataset is considered, so no integration is needed----

# Data Reduction 
# ------No reduction required, as there are considerable number of variables--------

# """"""Data Transformation""""""

# Normalize BMI using StandardScaler
scaler = StandardScaler()
bmi_scaled = scaler.fit_transform(data[['bmi']])
data['bmi_scaled'] = bmi_scaled

In [8]:
# """"""Data Discretization""""""""""
# Discretize Age
def discretized_age(age):
    if age <= 18: 
        return 0
    elif age <=39:
        return 1
    elif age <= 64: 
        return 2
    else:
        return 3
data['age_discretized'] = data['age'].apply(discretized_age)

# Discretize Blood Glucose Level 
def discretized_glucose(col):  
    if col < 100:
        return 0 
    elif 100 <= col <= 125:
        return 1
    else:
        return 2

data['glucose_discretized'] = data['blood_glucose_level'].apply(discretized_glucose)

In [10]:
data.head(10)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes,bmi_scaled,age_discretized,glucose_discretized
0,1,35.0,0,0,0,23.47,6.6,90,0,-0.686567,1,0
1,1,54.0,0,0,1,22.40,3.5,100,0,-0.847830,2,1
2,1,61.0,0,0,0,22.85,5.8,158,0,-0.780009,2,2
3,1,43.0,1,0,0,29.00,5.7,220,1,0.146876,2,2
4,1,7.0,0,0,0,18.50,6.2,158,0,-1.435611,0,2
5,0,29.0,0,0,0,27.75,6.5,158,0,-0.041515,1,2
6,0,77.0,0,0,0,30.38,7.5,126,1,0.354860,3,2
7,0,25.0,0,0,0,27.32,6.2,80,0,-0.106322,1,0
8,1,39.0,0,0,-2,27.32,6.6,159,0,-0.106322,1,2
9,0,21.0,0,0,0,27.32,5.8,85,0,-0.106322,1,0

In [14]:
#save the cleaned dataset at new location
data_new=data.to_csv("/Users/zahiramohammed/Desktop/DAPM_dataset_new_cleaned.csv")